// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ProtocolVersionProcedure from "../protocol_version_procedure";

export type ProtocolVersionArgs = __Infer<typeof ProtocolVersionProcedure.params>;
export type ProtocolVersionResult = __Infer<typeof ProtocolVersionProcedure.returnType>;

