// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActivateModuleReducer from "../activate_module_reducer";
import BeginWarpReducer from "../begin_warp_reducer";
import BuyUpgradeReducer from "../buy_upgrade_reducer";
import BuzzReducer from "../buzz_reducer";
import DeactivateModuleReducer from "../deactivate_module_reducer";
import DepositReducer from "../deposit_reducer";
import DockReducer from "../dock_reducer";
import JoinReducer from "../join_reducer";
import RepairReducer from "../repair_reducer";
import ReportPoseReducer from "../report_pose_reducer";
import SeedDemoReducer from "../seed_demo_reducer";
import SetHomeHiveReducer from "../set_home_hive_reducer";
import SetNameReducer from "../set_name_reducer";
import SetWeatherReducer from "../set_weather_reducer";
import SyncWorldReducer from "../sync_world_reducer";
import UndockReducer from "../undock_reducer";

export type ActivateModuleParams = __Infer<typeof ActivateModuleReducer>;
export type BeginWarpParams = __Infer<typeof BeginWarpReducer>;
export type BuyUpgradeParams = __Infer<typeof BuyUpgradeReducer>;
export type BuzzParams = __Infer<typeof BuzzReducer>;
export type DeactivateModuleParams = __Infer<typeof DeactivateModuleReducer>;
export type DepositParams = __Infer<typeof DepositReducer>;
export type DockParams = __Infer<typeof DockReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type RepairParams = __Infer<typeof RepairReducer>;
export type ReportPoseParams = __Infer<typeof ReportPoseReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;
export type SetHomeHiveParams = __Infer<typeof SetHomeHiveReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetWeatherParams = __Infer<typeof SetWeatherReducer>;
export type SyncWorldParams = __Infer<typeof SyncWorldReducer>;
export type UndockParams = __Infer<typeof UndockReducer>;

