// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u32().primaryKey().name("player_id"),
  cell: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.i16(),
  pitch: __t.i16(),
  aimYaw: __t.i16().name("aim_yaw"),
  aimPitch: __t.i16().name("aim_pitch"),
  tick: __t.u32(),
  hp: __t.u16(),
  maxHp: __t.u16().name("max_hp"),
  flags: __t.u8(),
});
