// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cell: __t.u32(),
  kind: __t.u8(),
  sourceKind: __t.u8().name("source_kind"),
  sourceId: __t.u32().name("source_id"),
  targetKind: __t.u8().name("target_kind"),
  targetId: __t.u32().name("target_id"),
  value: __t.u16(),
  aux: __t.u16(),
});
