// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  flyId: __t.u32().primaryKey().name("fly_id"),
  cell: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.i16(),
  vy: __t.i16(),
  vz: __t.i16(),
  yaw: __t.i16(),
  pitch: __t.i16(),
  kind: __t.u8(),
  hp: __t.u16(),
  state: __t.u8(),
  target: __t.u32(),
  tick: __t.u32(),
});
