// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  slot: __t.u8(),
  targetKind: __t.u8().name("target_kind"),
  targetId: __t.u32().name("target_id"),
  nextCycleAtMs: __t.u64().name("next_cycle_at_ms"),
  stopAfterCycle: __t.bool().name("stop_after_cycle"),
});
