// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u32().primaryKey().name("player_id"),
  honey: __t.u32(),
  cargo: __t.u16(),
  cargoGold: __t.u16().name("cargo_gold"),
  energy: __t.f32(),
  energyAt: __t.f64().name("energy_at"),
  hp: __t.u16(),
  lensLevel: __t.u8().name("lens_level"),
  gatlingLevel: __t.u8().name("gatling_level"),
  quiverLevel: __t.u8().name("quiver_level"),
  brushLevel: __t.u8().name("brush_level"),
  cargoLevel: __t.u8().name("cargo_level"),
  wingsLevel: __t.u8().name("wings_level"),
  armorLevel: __t.u8().name("armor_level"),
  antennaLevel: __t.u8().name("antenna_level"),
  nectarLevel: __t.u8().name("nectar_level"),
  dockedHive: __t.u8().name("docked_hive"),
  hivesVisited: __t.u16().name("hives_visited"),
  achievements: __t.u32(),
  deaths: __t.u32(),
  savedX: __t.f32().name("saved_x"),
  savedY: __t.f32().name("saved_y"),
  savedZ: __t.f32().name("saved_z"),
  savedFlags: __t.u8().name("saved_flags"),
});
